# Kind cluster configuration for Traefik
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # Map port 80 for web traffic
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        listenAddress: "0.0.0.0"
      # Map port 8080 for Traefik dashboard
      - containerPort: 8080
        hostPort: 8080
        protocol: TCP
        listenAddress: "0.0.0.0"
      # Map port 443 for HTTPS traffic
      - containerPort: 443
        hostPort: 443
        protocol: TCP
        listenAddress: "0.0.0.0"
  - role: worker
  - role: worker